version: "3"
services:
  db:
    image: mysql:5.7
    container_name: "mysql57"
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_c9JfShpj
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: pressman
      MYSQL_PASSWORD: c9JfShpj

  wordpress:
    image: wordpress:latest
    container_name: "wordpress"
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
      - ./wordpress/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    depends_on:
      - db
    ports:
      - 8088:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: pressman
      WORDPRESS_DB_PASSWORD: c9JfShpj

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin"
    # build:
    #   context: ./phpmyadmin
    #   dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80
    volumes:
      - /phpmyadmin/sessions:/sessions